### ISSUE TITLE
bug of sleep Pin definition

### ISSUE THREAD

**Issue by indexdb** [foldvarid93/JBC_SolderingStation#6]
change 
#define SLEEP_Pin GPIO_PIN_15
#define SLEEP_GPIO_Port GPIOA

to:

#define SLEEP_Pin GPIO_PIN_11
#define SLEEP_GPIO_Port GPIOC

**Comment by foldvarid93** [comment]
Why?

**Comment by indexdb** [comment]
pin 15 is encoder pin not sleep pin

**Comment by foldvarid93** [comment]
This issue only was on CubeIDE project. Problem fixed.
